"""
Django settings for tif2pdf project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-52ms+60(@4#49l)82_*xto&^ybpkte2!dor-!p11vle$-v$$6f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'django_celery_beat',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tif2pdf.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tif2pdf.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
}

# Folder mount point for the TIFs (e.g., mounted via Docker volume)
MOUNTED_DATA_DIR = Path(os.getenv("DATA_MOUNT_PATH", "/home/jc/project/fde_scanning/tif2pdf/test_files"))


# Celery configuration
# Uses RabbitMQ by default. Override with the environment variable
# `CELERY_BROKER_URL` if needed (e.g. amqp://user:password@host:5672//).
CELERY_BROKER_URL = os.environ.get(
    'CELERY_BROKER_URL', 'amqp://guest:guest@localhost:5672//'
)


CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'rpc://')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Heavy I/O Workload Optimizations (CRITICAL)

# Acknowledge tasks ONLY after the function returns successfully. 
# If the container crashes mid-conversion, RabbitMQ will requeue it.
CELERY_TASK_ACKS_LATE = True

# Prevent workers from reserving multiple heavy tasks in memory.
# They will only take 1 task at a time.
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# Limit the maximum number of concurrent tasks per worker to prevent disk thrashing.
# You can scale this by running more Docker containers rather than overloading one.
CELERY_WORKER_CONCURRENCY = 1 

# Optional: Set a hard time limit (in seconds) if a 16GB file gets stuck in an infinite loop.
# Example: 3600 seconds = 1 hour. Adjust based on your slowest expected conversion.
# CELERY_TASK_TIME_LIMIT = 1800 # 30 minutes
# CELERY_TASK_SOFT_TIME_LIMIT = 1800 # 30 minutes

CELERY_WORKER_MAX_MEMORY_PER_CHILD = 2000000 # 2GB - adjust based on your server's RAM and expected file sizes. This will restart the worker if it exceeds this memory limit, preventing crashes due to memory leaks or extremely large files.


# If the child worker process drops dead (OOM), instantly put the job back in the queue
CELERY_TASK_REJECT_ON_WORKER_LOST = False


CELERY_BEAT_SCHEDULE = {
    'sweep-orphaned-conversion-jobs-every-10-minutes': {
        'task': 'api.tasks.clean_orphaned_jobs',     # Update 'api' to your actual
        'schedule': crontab(minute='*/2'),           # Runs every 2 minutes
        # 'args': (),                                # Pass arguments here if your task needed them
    },
}
